version: "3"
services:
  front:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd to_do_list_front && yarn start"
    ports:
      - "8000:3000"
