version: "3"
services:
  front:
    build:
      context: .
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/front/node_modules
    command: sh -c "yarn start"
    ports:
      - "8000:3000"
